Controllers films users
RedokPaw/java-filmorate pull request #5
Opened 2024-03-14 17:38 UTC by RedokPaw

Added First Controllers and models

2024-03-15 17:20 UTC, dgumich requested changes

2024-03-15 17:20 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Реквест на создание фильма");
В логах нужно по больше информации: что за фильм, какой айди и тд. Это важно, потому что программисты часто работают с логами. Иногда это всё, что у тебя есть для разбора инцидента. Поэтому важно писать осмысленные сообщения

2024-03-15 17:20 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Ошибка при обновлении фильма: нет такого фильма в списке");
Аналогично, добавь айди фильма, что бы было понятно.
Просто представь: у тебя 10 таких запросов и 2 раза будет "Ошибка при обновлении фильма...". Вот сможешь сказать, какие фильмы не смогли обновить?

2024-03-15 17:20 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        throw new UpdateException("User update exception");
В исключения также передавай сообщения, которые дадут понять, что случилось. Добавь айди пользователя

2024-03-15 17:20 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/CreationException.java
> +public class CreationException extends Exception {
Кастомные исключения обычно делают от RuntimeException, а не просто Exception.  Тогда не надо городить try-catch блоки или писать их в названии метода.

2024-03-15 17:20 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/UpdateException.java
> +public class UpdateException extends Exception {
Аналогично, поменяй на RuntimeException

2024-03-15 17:20 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ValidationException.java
> +public class ValidationException extends Exception {
И тут поменяй родительский класс

2024-03-15 17:20 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @Email(message = "The string has to be a well-formed email address.")
На самом деле для валидации email нужно добавить еще одну аннотацию. Советую почитать доки по @Email, тогда станет понятно, какой кейс не покрывается ей=)

2024-03-15 17:20 UTC, dgumich commented on src/test/java/ru/yandex/practicum/filmorate/model/FilmTest.java
> +    static Validator validator;
Зачем поле статичное и почему не приватное?=)

2024-03-15 17:20 UTC, dgumich commented on src/test/java/ru/yandex/practicum/filmorate/model/UserTest.java
> +    static Validator validator;
И тут вопрос к статичному и почему не приватное?

2024-03-17 18:11 UTC, RedokPaw commented on src/test/java/ru/yandex/practicum/filmorate/model/FilmTest.java
> +    static Validator validator;
Поле статичное, потому что метод статичный с валидатором с @BeforeAll. Так что нужно статичное поле. Приватность исправил

2024-03-17 18:11 UTC, RedokPaw commented on src/test/java/ru/yandex/practicum/filmorate/model/UserTest.java
> +    static Validator validator;
Аналогично, метод с валидатором статичный, поэтому и поле статичное. Private добавил

2024-03-17 18:31 UTC, RedokPaw commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @Email(message = "The string has to be a well-formed email address.")
Если речь про null, то поправил)

2024-03-17 18:33 UTC, RedokPaw commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/CreationException.java
> +public class CreationException extends Exception {
Исправлено

2024-03-17 18:33 UTC, RedokPaw commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/UpdateException.java
> +public class UpdateException extends Exception {
Исправил

2024-03-17 18:37 UTC, RedokPaw commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Реквест на создание фильма");
Исправил

2024-03-17 18:39 UTC, RedokPaw commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Ошибка при обновлении фильма: нет такого фильма в списке");
Исправил

2024-03-17 18:39 UTC, RedokPaw commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        throw new UpdateException("User update exception");
Исправил

2024-03-17 18:39 UTC, RedokPaw commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ValidationException.java
> +public class ValidationException extends Exception {
Исправил

2024-03-18 16:47 UTC, dgumich commented on src/test/java/ru/yandex/practicum/filmorate/model/FilmTest.java
> +    static Validator validator;
А зачем метод статичный? У нас есть поле Validator, мы его хотим перед каждым тестом сетапить заново. Зачем для этого делать статичный метод? Он может быть простым методом.

2024-03-18 17:09 UTC, dgumich approved these changes

2024-03-18 17:49 UTC, RedokPaw commented on src/test/java/ru/yandex/practicum/filmorate/model/FilmTest.java
> +    static Validator validator;
@BeforeAll по спецификиции должен быть статичным.

2024-03-19 07:01 UTC, RedokPaw commented on pom.xml
> +        <dependency>
Видимо добавил случайно, уберу)

2024-03-19 08:53 UTC, RedokPaw commented on pom.xml
> +        <dependency>
Или я чего-то не понимаю

2024-03-19 08:53 UTC, RedokPaw commented on pom.xml
> +        <dependency>
Или я чего то не понял?
![image](https://github.com/RedokPaw/java-filmorate/assets/30343249/bfa533d2-63aa-4477-b878-cbbd1ededd8e)

2024-03-19 11:10 UTC, merged