RESTAPI, friends and like feature
RedokPaw/java-filmorate pull request #6
Opened 2024-04-09 15:02 UTC by RedokPaw

2024-04-09 20:34 UTC, dgumich requested changes

2024-04-09 20:34 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        return new ErrorResponse(e.getMessage());
Обычно, когда обрабатывают исключение (а тут по сути это и происходит) его логируют. Так что добавь во все хендлеры логирование.

2024-04-09 20:34 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (errors.hasErrors()) {
А зачем это делать? Если хочешь обработать валидацию спринга, то это тоже можно сделать через эксепшн хендлер. Тут про это есть https://www.baeldung.com/spring-boot-bean-validation

2024-04-09 20:34 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film updateFilm(@Valid @RequestBody Film film, BindingResult errors) {
Аналогично, не надо проверять ошибки в контроллере

2024-04-09 20:34 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User createNewUser(@Validated @RequestBody User user, BindingResult errors) {
И здесь не нужно проверять ошибки. Сделай это в хендлере

2024-04-09 20:34 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        if (films.containsKey(film.getId())) {
Проверка существует ли фильм - бизнес логика, ее надо вынести в сервисный класс.

2024-04-09 20:34 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private boolean isReleaseDateCorrect(LocalDate releaseDate) {
Валидация тоже часть бизнесс логики, надо вынести в сервисный слой.

2024-04-10 09:01 UTC, RedokPaw commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private boolean isReleaseDateCorrect(LocalDate releaseDate) {
Исправил

2024-04-10 09:02 UTC, RedokPaw commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        if (films.containsKey(film.getId())) {
Исправил и сделал то же самое и для всей другой логики в фильмах и юзерах

2024-04-10 09:25 UTC, RedokPaw commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (errors.hasErrors()) {
Исправил

2024-04-10 09:25 UTC, RedokPaw commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film updateFilm(@Valid @RequestBody Film film, BindingResult errors) {
Исправил

2024-04-10 09:25 UTC, RedokPaw commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User createNewUser(@Validated @RequestBody User user, BindingResult errors) {
Исправил

2024-04-10 20:47 UTC, dgumich requested changes

2024-04-10 20:47 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired
Надеюсь, понимаешь, что стоит за этой аннотацией=) Если нет, то советую разобраться.

2024-04-10 20:47 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return userStorage.deleteUser(user);
Смотри, если прям хочется сделать проверку, на то что, пользователь был перед удалением, то можно сначала удалить, если пользователь есть - он удалится из "бд" и сторедж вернет нам этого пользователя. Если его нет - то просто вернет null.
Юзер юзер =  userStorage.deleteUser(user)
иф (юзер == налл) тогда логируем и кидаем исключение. 
После блока иф - ретерн юзер. 
Чем это лучше? Тем что что к "бд" мы сходим один раз вместо двух=)

2024-04-10 20:47 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    public User deleteUser(User user) {
В принципе зачем нам тут пользователь? Можно просто передать айди пользователя, этого достаточно.
Так же лучше переименовать метод: делетЮзерБайАйди.

2024-04-10 20:47 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public Film deleteFilm(Film film) {
Аналогично и здесь, нам нужен не весь фильм, а только его айди. Соответственно и метод можно назвать по другому=)

2024-04-10 20:47 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public List<Film> getFilms() {
Советую поменять название метода на getAllFilms. Так понятно, что получаем все фильмы.

2024-04-10 20:47 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        friend.getFriends().add(user.getId());
Эта строка нам не нужна, мы уже добавили в строке 33 (user.getFriends().add(friend.getId()))

2024-04-10 20:47 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        friend.getFriends().remove(user.getId());
Аналогично, мы уже удалили айди друга в строке 49, так что повторно удалять не надо

2024-04-10 20:47 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.getFilmById(film.getId()) == null) {
Здесь можно сделать аналогично как в методе удаления пользователя.

2024-04-18 11:20 UTC, RedokPaw commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        friend.getFriends().add(user.getId());
Мы здесь добавляем всписок друзей друга первого юзера, а там в список друзей юзера друга)

2024-04-18 11:21 UTC, RedokPaw commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        friend.getFriends().remove(user.getId());
То же самое, что и выше, но то только удаляем

2024-04-18 11:23 UTC, merged