DB, DAOs, genres and MPA are added
RedokPaw/java-filmorate pull request #7
Opened 2024-04-19 10:06 UTC by RedokPaw

2024-04-20 03:19 UTC, dgumich requested changes

2024-04-20 03:19 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        System.out.println(film);
Это зачем?=)

2024-04-20 03:19 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .map(this::getGenreById)
Тут надо переписать и использовать джоин. Что получается: вместо одного запроса с джоином мы идем в базу для того, что бы получить сначала все айди жанров, а потом еще за каждым жанром в бд. Слишком много запросов.

2024-04-20 03:19 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                    getGenreById(genre.getId());
Аналогично и здесь, вместо одного запроса ходим столько раз, сколько жанров у фильма. Надо переделать на один запрос.

2024-04-20 03:19 UTC, dgumich commented on src/main/resources/schema.sql
> +    NAME     CHARACTER VARYING,
Обычно пишут VARCHAR вместо CHARACTER VARYING. Так же необходимо указать длину в скобочках. Например: VARCHAR(10) или VARCHAR(231) и тд.

2024-04-21 10:30 UTC, RedokPaw commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        System.out.println(film);
ой ) поправил

2024-04-21 11:08 UTC, RedokPaw commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .map(this::getGenreById)
Переписал

2024-04-21 11:38 UTC, RedokPaw commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                    getGenreById(genre.getId());
Поправил

2024-04-21 11:38 UTC, RedokPaw commented on src/main/resources/schema.sql
> +    NAME     CHARACTER VARYING,
почему то подумал, что в H2 нету varchar, поправил)

2024-04-21 22:47 UTC, dgumich approved these changes

2024-04-21 22:47 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/UserIsNullException.java
> +public class UserIsNullException extends RuntimeException {
Я бы поменял название исключения, больше бы подошло UserIsNotFoundException

2024-04-21 22:47 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .sorted(Comparator.comparingInt(o -> (filmStorage.getAllFilmLikes(((Film) o).getId()).size())).reversed())
Тут тоже не очень получается: по идее лайки должны быть полем у фильма (как было с хешсетом). А теперь для каждого фильма ходим и вытаскиваем лайки из БД. Тоже советую переделать на джойны

2024-04-21 22:47 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            } catch (EmptyResultDataAccessException e) {
Немного не понимаю двойную проверку: мы и на null проверяем (что по логике значит, что ничего не найдено) и на EmptyResultDataAccessException, что по идее значит тоже самое.

2024-05-14 09:52 UTC, merged